### ISSUE TITLE
Question about ssh and starship promt

### ISSUE THREAD

**Issue by NicolasVanDyck** [ChristianLempa/dotfiles#15]
I have a question about ssh and starship.
So i have customized my zsh shell with starship on my wsl2 linux . Now whenever i ssh to a server everything changes. I just get username@hostname: Is this normal? Do i need to customize every server? Or should starship just adjust the promt with the user and hostname of the server?

**Comment by peupeuv** [comment]
Hi,
Yes, this is expected behavior. When you SSH to a remote server, your shell is running on the remote server, not on your local machine. Therefore, the configuration and prompt settings that you have set up on your local machine will not be applied to the remote shell session.
To use the same prompt settings on the remote server, you should install and configure Starship on every remote server as well. 
if you have multiple remote servers you can automate the task using ansible and a dotfiles repo.
you can check  https://github.com/peupeuv/dotfiles
